export interface Recipe {
  title: string;
  user: string;
  img: string;
  description: string;
}

export const recipes: Recipe[] = [
  {
    title: 'Mac & cheese',
    user: 'Username',
    img: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=400&q=80',
    description: 'Przepis na Mac & cheese: Ugotuj makaron, przygotuj sos serowy, wymieszaj i zapiecz.',
  },
  {
    title: 'Kurczak złocisty',
    user: 'Username',
    img: 'https://images.unsplash.com/photo-1519864600265-abb23847ef2c?auto=format&fit=crop&w=400&q=80',
    description: 'Przepis na Kurczaka złocistego: Zamarynuj kurczaka, usmaż na złoto, podawaj z ziemniakami.',
  },
  {
    title: 'Zupa krem z dyni',
    user: 'Username',
    img: 'https://images.unsplash.com/photo-1502741338009-cac2772e18bc?auto=format&fit=crop&w=400&q=80',
    description: 'Przepis na Zupę krem z dyni: Ugotuj dynię, zmiksuj z bulionem, dopraw śmietaną.',
  },
  {
    title: 'Omlet warzywny',
    user: 'Username',
    img: 'https://images.unsplash.com/photo-1464306076886-debca5e8a6b0?auto=format&fit=crop&w=400&q=80',
    description: 'Przepis na Omlet warzywny: Roztrzep jajka, dodaj warzywa, usmaż na patelni.',
  },
  {
    title: 'Owsianka z borówkami',
    user: 'Username',
    img: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=400&q=80',
    description: 'Przepis na Owsiankę z borówkami: Ugotuj płatki owsiane, dodaj borówki i miód.',
  },
  {
    title: 'Smoothie',
    user: 'Username',
    img: 'https://images.unsplash.com/photo-1519864600265-abb23847ef2c?auto=format&fit=crop&w=400&q=80',
    description: 'Przepis na Smoothie: Zblenduj owoce z jogurtem i miodem.',
  },
  {
    title: 'Pancakes',
    user: 'Username',
    img: 'https://images.unsplash.com/photo-1502741338009-cac2772e18bc?auto=format&fit=crop&w=400&q=80',
    description: 'Przepis na Pancakes: Przygotuj ciasto, smaż placuszki, podawaj z syropem klonowym.',
  },
  {
    title: 'Pizza Margherita',
    user: 'Username',
    img: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=400&q=80',
    description: 'Przepis na Pizzę Margherita: Przygotuj ciasto, sos pomidorowy, mozzarellę i zapiecz.',
  },
  {
    title: 'Lasagne',
    user: 'Username',
    img: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=400&q=80',
    description: 'Przepis na Lasagne: Ułóż warstwy makaronu, mięsa i sosu, zapiecz.',
  },
  {
    title: 'Tortilla',
    user: 'Username',
    img: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=400&q=80',
    description: 'Przepis na Tortillę: Zawiń ulubione składniki w placek tortilli.',
  },
  {
    title: 'Sałatka grecka',
    user: 'Username',
    img: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=400&q=80',
    description: 'Przepis na Sałatkę grecką: Pokrój warzywa, dodaj fetę i oliwki.',
  },
  {
    title: 'Burger',
    user: 'Username',
    img: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=400&q=80',
    description: 'Przepis na Burgera: Usmaż kotlet, dodaj bułkę i ulubione dodatki.',
  },
  {
    title: 'Risotto',
    user: 'Username',
    img: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=400&q=80',
    description: 'Przepis na Risotto: Podsmaż ryż, dodaj bulion i mieszaj do miękkości.',
  },
  {
    title: 'Sushi',
    user: 'Username',
    img: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=400&q=80',
    description: 'Przepis na Sushi: Zawiń ryż i dodatki w nori.',
  },
  {
    title: 'Kebab',
    user: 'Username',
    img: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=400&q=80',
    description: 'Przepis na Kebab: Zawiń mięso i warzywa w chlebek pita.',
  },
  {
    title: 'Gulasz',
    user: 'Username',
    img: 'https://images.unsplash.com/photo-1519864600265-abb23847ef2c?auto=format&fit=crop&w=400&q=80',
    description: 'Przepis na Gulasz: Duś mięso z warzywami i przyprawami.',
  },
  {
    title: 'Tarta owocowa',
    user: 'Username',
    img: 'https://images.unsplash.com/photo-1464306076886-debca5e8a6b0?auto=format&fit=crop&w=400&q=80',
    description: 'Przepis na Tartę owocową: Przygotuj kruche ciasto, dodaj owoce i zapiecz.',
  },
  {
    title: 'Curry',
    user: 'Username',
    img: 'https://images.unsplash.com/photo-1519864600265-abb23847ef2c?auto=format&fit=crop&w=400&q=80',
    description: 'Przepis na Curry: Podsmaż warzywa, dodaj pastę curry i mleko kokosowe.',
  },
  {
    title: 'Ramen',
    user: 'Username',
    img: 'https://images.unsplash.com/photo-1502741338009-cac2772e18bc?auto=format&fit=crop&w=400&q=80',
    description: 'Przepis na Ramen: Ugotuj makaron, dodaj bulion i dodatki.',
  },
  {
    title: 'Pierogi',
    user: 'Username',
    img: 'https://images.unsplash.com/photo-1464306076886-debca5e8a6b0?auto=format&fit=crop&w=400&q=80',
    description: 'Przepis na Pierogi: Zagnieć ciasto, nadziej farszem i ugotuj.',
  },
  {
    title: 'Kopytka',
    user: 'Username',
    img: 'https://images.unsplash.com/photo-1519864600265-abb23847ef2c?auto=format&fit=crop&w=400&q=80',
    description: 'Przepis na Kopytka: Ugotuj ziemniaki, zagnieć z mąką, ugotuj kluski.',
  },
  {
    title: 'Sernik',
    user: 'Username',
    img: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=400&q=80',
    description: 'Przepis na Sernik: Przygotuj masę serową, upiecz na spodzie z herbatników.',
  },
  {
    title: 'Szarlotka',
    user: 'Username',
    img: 'https://images.unsplash.com/photo-1464306076886-debca5e8a6b0?auto=format&fit=crop&w=400&q=80',
    description: 'Przepis na Szarlotkę: Przygotuj kruche ciasto, dodaj jabłka i zapiecz.',
  },
  {
    title: 'Brownie',
    user: 'Username',
    img: 'https://images.unsplash.com/photo-1519864600265-abb23847ef2c?auto=format&fit=crop&w=400&q=80',
    description: 'Przepis na Brownie: Przygotuj masę czekoladową, upiecz w formie.',
  },
  {
    title: 'Tiramisu',
    user: 'Username',
    img: 'https://images.unsplash.com/photo-1502741338009-cac2772e18bc?auto=format&fit=crop&w=400&q=80',
    description: 'Przepis na Tiramisu: Ułóż warstwy biszkoptów i kremu z mascarpone.',
  },
  {
    title: 'Ciasto marchewkowe',
    user: 'Username',
    img: 'https://images.unsplash.com/photo-1464306076886-debca5e8a6b0?auto=format&fit=crop&w=400&q=80',
    description: 'Przepis na Ciasto marchewkowe: Zetrzyj marchew, dodaj do ciasta i upiecz.',
  },
  {
    title: 'Lody waniliowe',
    user: 'Username',
    img: 'https://images.unsplash.com/photo-1519864600265-abb23847ef2c?auto=format&fit=crop&w=400&q=80',
    description: 'Przepis na Lody waniliowe: Ubij śmietankę z wanilią, zamroź.',
  },
  {
    title: 'Lody czekoladowe',
    user: 'Username',
    img: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=400&q=80',
    description: 'Przepis na Lody czekoladowe: Ubij śmietankę z kakao, zamroź.',
  },
  {
    title: 'Lody truskawkowe',
    user: 'Username',
    img: 'https://images.unsplash.com/photo-1502741338009-cac2772e18bc?auto=format&fit=crop&w=400&q=80',
    description: 'Przepis na Lody truskawkowe: Ubij śmietankę z truskawkami, zamroź.',
  },
  {
    title: 'Koktajl owocowy',
    user: 'Username',
    img: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=400&q=80',
    description: 'Przepis na Koktajl owocowy: Zblenduj owoce z mlekiem lub jogurtem.',
  },
  {
    title: 'Zupa pomidorowa',
    user: 'Username',
    img: 'https://images.unsplash.com/photo-1519864600265-abb23847ef2c?auto=format&fit=crop&w=400&q=80',
    description: 'Przepis na Zupę pomidorową: Ugotuj pomidory z bulionem, zmiksuj.',
  },
  {
    title: 'Zupa ogórkowa',
    user: 'Username',
    img: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=400&q=80',
    description: 'Przepis na Zupę ogórkową: Ugotuj ogórki z ziemniakami i bulionem.',
  },
  {
    title: 'Zupa grzybowa',
    user: 'Username',
    img: 'https://images.unsplash.com/photo-1502741338009-cac2772e18bc?auto=format&fit=crop&w=400&q=80',
    description: 'Przepis na Zupę grzybową: Ugotuj grzyby z warzywami i śmietaną.',
  },
  {
    title: 'Zupa jarzynowa',
    user: 'Username',
    img: 'https://images.unsplash.com/photo-1464306076886-debca5e8a6b0?auto=format&fit=crop&w=400&q=80',
    description: 'Przepis na Zupę jarzynową: Ugotuj warzywa z bulionem.',
  },
  {
    title: 'Zupa cebulowa',
    user: 'Username',
    img: 'https://images.unsplash.com/photo-1519864600265-abb23847ef2c?auto=format&fit=crop&w=400&q=80',
    description: 'Przepis na Zupę cebulową: Podsmaż cebulę, dodaj bulion i zapiecz z grzanką.',
  },
];

export const recipeDescriptions: string[] = [
  'Przepis na Mac & cheese: Ugotuj makaron, przygotuj sos serowy, wymieszaj i zapiecz.',
  'Przepis na Kurczaka złocistego: Zamarynuj kurczaka, usmaż na złoto, podawaj z ziemniakami.',
  'Przepis na Zupę krem z dyni: Ugotuj dynię, zmiksuj z bulionem, dopraw śmietaną.',
  'Przepis na Omlet warzywny: Roztrzep jajka, dodaj warzywa, usmaż na patelni.',
  'Przepis na Owsiankę z borówkami: Ugotuj płatki owsiane, dodaj borówki i miód.',
  'Przepis na Smoothie: Zblenduj owoce z jogurtem i miodem.',
  'Przepis na Pancakes: Przygotuj ciasto, smaż placuszki, podawaj z syropem klonowym.',
  'Przepis na Pizzę Margherita: Przygotuj ciasto, sos pomidorowy, mozzarellę i zapiecz.',
  'Przepis na Lasagne: Ułóż warstwy makaronu, mięsa i sosu, zapiecz.',
  'Przepis na Tortillę: Zawiń ulubione składniki w placek tortilli.',
  'Przepis na Sałatkę grecką: Pokrój warzywa, dodaj fetę i oliwki.',
  'Przepis na Burgera: Usmaż kotlet, dodaj bułkę i ulubione dodatki.',
  'Przepis na Risotto: Podsmaż ryż, dodaj bulion i mieszaj do miękkości.',
  'Przepis na Sushi: Zawiń ryż i dodatki w nori.',
  'Przepis na Kebab: Zawiń mięso i warzywa w chlebek pita.',
  'Przepis na Gulasz: Duś mięso z warzywami i przyprawami.',
  'Przepis na Tartę owocową: Przygotuj kruche ciasto, dodaj owoce i zapiecz.',
  'Przepis na Curry: Podsmaż warzywa, dodaj pastę curry i mleko kokosowe.',
  'Przepis na Ramen: Ugotuj makaron, dodaj bulion i dodatki.',
  'Przepis na Pierogi: Zagnieć ciasto, nadziej farszem i ugotuj.',
  'Przepis na Kopytka: Ugotuj ziemniaki, zagnieć z mąką, ugotuj kluski.',
  'Przepis na Sernik: Przygotuj masę serową, upiecz na spodzie z herbatników.',
  'Przepis na Szarlotkę: Przygotuj kruche ciasto, dodaj jabłka i zapiecz.',
  'Przepis na Brownie: Przygotuj masę czekoladową, upiecz w formie.',
  'Przepis na Tiramisu: Ułóż warstwy biszkoptów i kremu z mascarpone.',
  'Przepis na Ciasto marchewkowe: Zetrzyj marchew, dodaj do ciasta i upiecz.',
  'Przepis na Lody waniliowe: Ubij śmietankę z wanilią, zamroź.',
  'Przepis na Lody czekoladowe: Ubij śmietankę z kakao, zamroź.',
  'Przepis na Lody truskawkowe: Ubij śmietankę z truskawkami, zamroź.',
  'Przepis na Koktajl owocowy: Zblenduj owoce z mlekiem lub jogurtem.',
  'Przepis na Zupę pomidorową: Ugotuj pomidory z bulionem, zmiksuj.',
  'Przepis na Zupę ogórkową: Ugotuj ogórki z ziemniakami i bulionem.',
  'Przepis na Zupę grzybową: Ugotuj grzyby z warzywami i śmietaną.',
  'Przepis na Zupę jarzynową: Ugotuj warzywa z bulionem.',
  'Przepis na Zupę cebulową: Podsmaż cebulę, dodaj bulion i zapiecz z grzanką.',
]; 